const sampleBuildingData = [
  {
    id: "1",
    name: "Tòa nhà D4 - Chung cư cao cấp",
    landlord: {
      id: "1",
      first_name: "Nguyễn",
      last_name: "Văn An",
      email: "nguyenvanan@email.com",
      phone: "0123456789",
      avatar: {
        id: "avatar1",
        storage: "local",
        filename_disk: "avatar1.jpg",
        filename_download: "avatar1.jpg",
        title: "Avatar Nguyễn Văn An",
        type: "image/jpeg",
        folder: null,
        uploaded_by: "1",
        uploaded_on: "2024-01-15T10:00:00Z",
        modified_by: null,
        modified_on: null,
        charset: null,
        filesize: "150000",
        width: 200,
        height: 200,
        duration: null,
        embed: null,
        description: null,
        location: null,
        tags: null,
        metadata: { tempUrl: "/landlord-avatar.jpg" },
      },
    },
    year_constructions: "2020",
    total_rooms: 120,
    total_floors: 15,
    area: "Trung tâm thành phố",
    city: "Hà Nội",
    district: {
      id: "1",
      name: "Hoàn Kiếm",
      photo: {
        id: "district1",
        storage: "local",
        filename_disk: "hoankiem.jpg",
        filename_download: "hoankiem.jpg",
        title: "Quận Hoàn Kiếm",
        type: "image/jpeg",
        folder: null,
        uploaded_by: "1",
        uploaded_on: "2024-01-15T10:00:00Z",
        modified_by: null,
        modified_on: null,
        charset: null,
        filesize: "200000",
        width: 400,
        height: 300,
        duration: null,
        embed: null,
        description: null,
        location: null,
        tags: null,
        metadata: { tempUrl: "/ho-n-ki-m-district.jpg" },
      },
    },
    ward: "Phường Hàng Bài",
    specific_address: "321 Trần Hưng Đạo",
    building_image: {
      id: "building1",
      storage: "local",
      filename_disk: "building1.jpg",
      filename_download: "building1.jpg",
      title: "Tòa nhà D4",
      type: "image/jpeg",
      folder: null,
      uploaded_by: "1",
      uploaded_on: "2024-01-15T10:00:00Z",
      modified_by: null,
      modified_on: null,
      charset: null,
      filesize: "500000",
      width: 800,
      height: 600,
      duration: null,
      embed: null,
      description: null,
      location: null,
      tags: null,
      metadata: { tempUrl: "/modern-apartment-building.png" },
    },
    description:
      "Tòa nhà chung cư cao cấp với đầy đủ tiện nghi hiện đại, vị trí trung tâm thành phố, gần các trường đại học và khu vực thương mại.",
    google_map_link: "https://maps.google.com/?q=21.0285,105.8542",
    lat: 21.0285,
    lng: 105.8542,
  },
  {
    id: "2",
    name: "Nhà trọ sinh viên Green House",
    landlord: {
      id: "2",
      first_name: "Trần",
      last_name: "Thị Bình",
      email: "tranthibinh@email.com",
      phone: "0987654321",
    },
    year_constructions: "2018",
    total_rooms: 45,
    total_floors: 5,
    area: "Gần trường đại học",
    city: "Hà Nội",
    district: {
      id: "2",
      name: "Cầu Giấy",
      photo: {
        id: "district2",
        storage: "local",
        filename_disk: "caugiay.jpg",
        filename_download: "caugiay.jpg",
        title: "Quận Cầu Giấy",
        type: "image/jpeg",
        folder: null,
        uploaded_by: "1",
        uploaded_on: "2024-01-15T10:00:00Z",
        modified_by: null,
        modified_on: null,
        charset: null,
        filesize: "180000",
        width: 400,
        height: 300,
        duration: null,
        embed: null,
        description: null,
        location: null,
        tags: null,
        metadata: { tempUrl: "/c-u-gi-y-district.jpg" },
      },
    },
    ward: "Phường Dịch Vọng",
    specific_address: "156 Xuân Thủy",
    building_image: {
      id: "building2",
      storage: "local",
      filename_disk: "building2.jpg",
      filename_download: "building2.jpg",
      title: "Green House",
      type: "image/jpeg",
      folder: null,
      uploaded_by: "2",
      uploaded_on: "2024-01-15T10:00:00Z",
      modified_by: null,
      modified_on: null,
      charset: null,
      filesize: "450000",
      width: 800,
      height: 600,
      duration: null,
      embed: null,
      description: null,
      location: null,
      tags: null,
      metadata: { tempUrl: "/student-dormitory-green-building.jpg" },
    },
    description:
      "Nhà trọ dành cho sinh viên với giá cả phải chăng, môi trường sạch sẽ, an toàn. Gần các trường đại học lớn và có đầy đủ tiện ích sinh hoạt.",
    google_map_link: "https://maps.google.com/?q=21.0378,105.7804",
    lat: 21.0378,
    lng: 105.7804,
  },
  {
    id: "3",
    name: "Khu nhà trọ Sunshine",
    landlord: {
      id: "3",
      first_name: "Lê",
      last_name: "Minh Châu",
      email: "leminhchau@email.com",
      phone: "0912345678",
    },
    year_constructions: "2019",
    total_rooms: 80,
    total_floors: 8,
    area: "Khu công nghiệp",
    city: "Hà Nội",
    district: {
      id: "3",
      name: "Thanh Xuân",
      photo: {
        id: "district3",
        storage: "local",
        filename_disk: "thanhxuan.jpg",
        filename_download: "thanhxuan.jpg",
        title: "Quận Thanh Xuân",
        type: "image/jpeg",
        folder: null,
        uploaded_by: "1",
        uploaded_on: "2024-01-15T10:00:00Z",
        modified_by: null,
        modified_on: null,
        charset: null,
        filesize: "220000",
        width: 400,
        height: 300,
        duration: null,
        embed: null,
        description: null,
        location: null,
        tags: null,
        metadata: { tempUrl: "/thanh-xu-n-district.jpg" },
      },
    },
    ward: "Phường Nhân Chính",
    specific_address: "89 Lê Văn Lương",
    building_image: {
      id: "building3",
      storage: "local",
      filename_disk: "building3.jpg",
      filename_download: "building3.jpg",
      title: "Sunshine Building",
      type: "image/jpeg",
      folder: null,
      uploaded_by: "3",
      uploaded_on: "2024-01-15T10:00:00Z",
      modified_by: null,
      modified_on: null,
      charset: null,
      filesize: "480000",
      width: 800,
      height: 600,
      duration: null,
      embed: null,
      description: null,
      location: null,
      tags: null,
      metadata: { tempUrl: "/modern-residential-building-sunshine.jpg" },
    },
    description:
      "Khu nhà trọ hiện đại dành cho người đi làm, gần các khu công nghiệp và trung tâm thương mại. Đầy đủ tiện nghi và dịch vụ hỗ trợ.",
    google_map_link: "https://maps.google.com/?q=20.9967,105.8019",
    lat: 20.9967,
    lng: 105.8019,
  },
];
